---
title: "Research"
output:
  html_document:
    theme: cosmo
---

**Research Fields**: Applied Macroeconomics, Economic Growth and Distribution, Inequality, Business Cycles, Climate Macroeconomics. 

### Publications

**"Rethinking growth and inequality in the US: What is the role of measurement of GDP?" *International Review of Applied Economics* 35:3-4, 551-576. https://doi.org/10.1080/02692171.2021.1892038 **

**Abstract**: Five sectors have increased their contribution to US GDP growth since 1973: professional-business services (PBS), finance, information, healthcare, and arts-entertainment. Among these, however, finance, healthcare, and PBS have questionable foundations for being regarded as final consumption of households. Contra published National Income and Product Accounts, treating expenditures on finance, healthcare, and PBS as intermediate consumption reveals a significantly different picture of US economic growth, including i) a deeper slowdown of real output growth since 1973; ii) a more moderate rise in consumption share since 1980; and iii) a sharper decline in labor share, defined as the compensation of employees over GDP since 1985. Through a measurement approach, this paper thus contributes to the literature on secular stagnation and rising inequality in the United States.

**"A sectoral approach to measuring output gap: Evidence from 20 US sectors over 1948-2020." *Macroeconomic Dynamics*, 1-23. https://doi.org/10.1017/S1365100522000141**



**Abstract**: The existing output gap measures for the US economy rely on aggregate data and assume a constant output gap over sectors (see Coibion et al. (2018) and Owyang et al. (2018)); however, each sector has its cycle, which does not necessarily match the business cycle (Burns and Mitchell, 1946). By modeling sectoral cycles based on their investment cycles with a non-parametric method, I estimate output gaps of 20 US sectors over 1948--2020. The weighted mean output gap indicates a persistent spare capacity in the last business cycle, pointing to insufficient stabilization policies behind secular stagnation. Phillips curve estimations with the weighted quartiles of sectoral output gaps show that the output gap of bottleneck sectors (weighted Q3) is correlated strongly with inflation over 1950--2020. Policymakers can track bottleneck sectors to mitigate inflationary pressures while supporting the sectors with negative output gaps to stabilize the output at its potential. My findings show that it is possible to produce more output by sector-level demand supporting policies without generating inflation.

### Working papers 

**"A Climate-Fiscal Policy Mix to Achieve Türkiye’s Net-Zero Ambition under Feasibility Constraints." (with Christian Schoder) Policy Research working paper ; no. WPS 10551 Washington, D.C. : World Bank Group.**


**Abstract**: This paper employs an estimated dynamic stochastic open-economy macro framework to identify policy interventions that allow Türkiye to achieve net-zero emissions by 2053 while respecting important feasibility constraints such as fiscal consolidation and sovereign debt stability as well as compensation of low-income households. The policy mix includes a carbon tax, a renewable energy subsidy, transfer payments, public infrastructure investments, a bad bank for stranded fossil fuel assets, and the phase-out of fossil fuel subsidies and public investment. Although the proposed policy package has only moderate effects on gross domestic product, transition risks involve declining exports and fossil asset stranding. The paper highlights the importance of transparent policy communication and a credible commitment to the net-zero agenda to ensure an orderly transition. Improving the rule of law and access to green finance considerably support the private sector-led low-carbon transition.

### Work in Progress

**"Revisiting Macroeconomic Fluctuations in the Euro Area: An Estimated Dynamic Stochastic Disequilibrium Model." (with Christian Schoder)**

**"OMEGA - An Open-Economy Multi-Sector Endogenous-Growth Assessment Model for Climate Policy Analysis in an Emerging Market Context." (with Christian Schoder)**
