---
title: "Teaching"
output:
  html_document:
    theme: cosmo
---

My teaching fields are applied macroeconomics, microeconomic theory, econometrics, mathematical economics and national income accounting. 

### Teaching Fellow (Instructor of Note)

**Quantitative Reasoning II, Eugene Lang College of Liberal Arts, New York, Spring 2021.** 

**Statistics for Social Sciences, Eugene Lang College of Liberal Arts, New York, Fall 2018, Fall 2019.**

(Responsible for creating syllabus, lecturing, organizing computer lab sessions, designing assignments and the assessment.)

### Teaching Assistant 

**Further Topics in Advanced Political Economy, taught by Duncan Foley, The New School, New York, Spring 2021.** 

(Responsible for organizing weekly online lab meetings and discussions.)

**Math for Economics, The New School, New York, Fall 2020.** 

(Responsible for organizing weekly online lab meetings and the assessment.)

**Ph.D. Microeconomics, taught by M. Ali Khan, The New School, New York, Spring 2019, Spring 2020.** 

(Responsible for organizing weekly lab meetings.)

**M.A. Microeconomics, taught by Sahar Parsa, New York University, Fall 2019.**

(Responsible for organizing weekly problem solving sessions and the assessment of weekly assignments.)


### Adjunct Lecturer

**Macroeconomics, New York City College of Technology, New York, Fall 2018, Spring 2019, Fall 2020.** 

(Responsible for creating syllabus, lecturing, designing assignments and the assessment.)


### Tutoring

**Mathematics Tutor, The New School University Learning Center, New York, February 2017 - December 2019.**




 

